export const SET_MENU_FILE_STRUCTURE = 'SET_MENU_FILE_STRUCTURE'
export const SET_PROBLEMS = 'SET_PROBLEMS'
export const SET_MENU_POINTER = 'SET_MENU_POINTER'
export const SET_PROBLEM_POINTER = 'SET_PROBLEM_POINTER'
export const CLEAR_PROBLEM_POINTER = "CLEAR_PROBLEM_POINTER"